
package org.havi.ui.event;

/*The HActionListener interface enables the reception of HActionEvent events,as generated by 
objects implementing HActionable .The parameters to the constructors are as follows,in 
cases where parameters are not used,then the constructor should use the default 
values. */

public interface HActionListener extends java.awt.event.ActionListener {


}
