
-include ../../Make.config

OBJS = vera.ttf  verabd.ttf  verabi.ttf  verait.ttf  veramo.ttf  veramobd.ttf  veramobi.ttf  veramoit.ttf  verase.ttf  verasebd.ttf

all:

clean:

install:
	@install -d $(MHPFONTDIR)
	@cp $(OBJS) $(MHPFONTDIR)
