
package org.havi.ui.event;

/*The HAdjustmentListener interface enables the reception of HAdjustmentEvent ,as generated 
by objects implementing HAdjustmentValue .The parameters to the constructors are as 
follows,in cases where parameters are not used,then the constructor should use the default 
values. */

public interface HAdjustmentListener extends java.util.EventListener {

/*
Called when the value of the component has started to be changed,is changed,or has  nished changing. Parameters: e -is 
the HAdjustmentEvent generated by the object implementing HAdjustmentValue . */
public void valueChanged(HAdjustmentEvent e);



}
