
package org.havi.ui.event;

/*The HFocusListener interface enables the reception of HFocusEvent events,as generated by 
objects implementing HNavigable .The parameters to the constructors are as follows,in 
cases where parameters are not used,then the constructor should use the default 
values. */

public interface HFocusListener extends java.awt.event.FocusListener {


}
