
package org.havi.ui.event;

import org.havi.ui.HItemValue;
/*An HItemEvent event is used to interact with a component implementing the 
HSelectionInputPreferred interface as follows: " An HItemEvent event may be sent from the 
HAVi system to the component to change the state of the com-ponent, and the selection set 
held by the component. " An HItemEvent event is sent from the component to all registered 
HItemListener when a change to the component state or selection set occurs. The HItemEvent 
event class therefore provides support for selecting and clearing individual elements, 
selecting or clearing all elements and managing the currently focused element,i.e.the item 
whose selection state is toggled by some user interaction. All interoperable HAVi 
components which expect to receive HItemEvent events should implement the 
HSelectionInputPreferred interface. */

public class HItemEvent extends java.awt.AWTEvent {

/*
An item event with this id is sent from the component whenever an item is added to the selection set of an HItemValue 
component.Note that events of this type are silently ignored if they are sent to the 
component. */
public static final int ITEM_SELECTED = 2008;


/*
An item event with this id is sent to or from the component whenever the entire selection set of an HItemValue component 
is removed. */
public static final int ITEM_SELECTION_CLEARED = 2010;


/*
An item event with this id is sent to or from the component whenever the current item of an HItemValue component 
changes. */
public static final int ITEM_SET_CURRENT = 2011;


/*
An item event with this id is sent to or from the component whenever the current item of an HItemValue component changes 
to the next item in the group. */
public static final int ITEM_SET_NEXT = 2013;


/*
An item event with this id is sent to or from the component whenever the current item of an HItemValue component changes 
to the previous item in the group. */
public static final int ITEM_SET_PREVIOUS = 2012;


/*
An item event with this id indicates that the selection of an HItemValue component may be about to change.This event is 
sent to or from the component when the user causes the component to enter selection mode.Note that it is a platform 
speci  c implementation option for such components to enter selection mode automatically e.g.when they receive input 
focus.In such a case the order in which the HFocusEvent and HItemEvent are sent is platform speci  
c. */
public static final int ITEM_START_CHANGE = 2006;


/*
An item event with this id indicates that the selection of an HItemValue component has been  nally set.This event is 
sent to or from the component when the user causes the component to leave selection mode.Note that it is a platform 
speci  c implementation option for such components to leave selection mode automatically e.g.when they lose input 
focus.In such a case the order in which the HFocusEvent and HItemEvent are sent is platform 
specific. */
public static final int ITEM_END_CHANGE = 2014;


/*
An item event with this id is sent from the component whenever an item is removed from the selection set of an 
HItemValue component.Note that events of this type are silently ignored if they are sent to the 
component. */
public static final int ITEM_CLEARED = 2009;


/*
An item event with this id may be sent to an HItemValue component to toggle the selection state of the currently focused 
item.Note that events of this type are never sent to listeners from the component;instead an event of type ITEM_SELECTED 
or ITEM_CLEARED is sent in response to an event with this id,depending on the new state of the currently focused 
item. */
public static final int ITEM_TOGGLE_SELECTED = 2007;


/*
The  rst integer id in the range of event ids supported by the HItemEvent class. */
public static final int ITEM_FIRST = 2006;


/*
The last integer id in the range of event ids supported by the HItemEvent class. */
public static final int ITEM_LAST = 2014;

protected Object item;
/*
Constructs an HItemEvent . Parameters: source -The HItemValue component whose value or current item has been modi  ed. 
id -The event id of the HItemEvent generated by the HItemValue component.This is the value that will be returned by the 
event object's getID method. item -The item which caused the change,or null if this information is not available.This 
information shall be provided if the event id is one of ITEM_SELECTED or ITEM_CLEARED 
. */
public HItemEvent(HItemValue source, int id, java.lang.Object anItem) {
   super(source, id);
   item=anItem;
}

/*
Retrieve the item which caused this HItemEvent .This information is not available for the ITEM_SELECTION_CLEARED event 
id. Returns: the item which was selected or cleared,or became the current item,or null if this information is not 
available for this event. */
public java.lang.Object getItem() {
   return item;
}


}
