
package org.havi.ui.event;

/*The HItemListener interface enables the reception of HItemEvent ,as generated by objects 
implementing HItemValue .The parameters to the constructors are as follows,in cases where 
parameters are not used,then the constructor should use the default 
values. */

public interface HItemListener extends java.util.EventListener {

/*
Called when a change to the current item of the HItemValue occurs. Parameters: e -is the HItemEvent generated by the 
object implementing HItemValue . */
public void currentItemChanged(HItemEvent e);


/*
Called when a change to the set of selected items held by the HItemValue occurs. Parameters: e -is the HItemEvent 
generated by the object implementing HItemValue. */
public void selectionChanged(HItemEvent e);



}
