
package javax.tv.service.selection;

/*

The <code>ServiceContextListener</code> interface is implemented by
 applications wishing to receive events related to service contexts.

*/
public interface ServiceContextListener extends java.util.EventListener {

/*
 
 Notifies the ServiceContextListener of an event
 generated by a ServiceContext . 
 
 
 
 Parameters:  e - The generated event. 
 
 
*/

public void receiveServiceContextEvent ( ServiceContextEvent e);



}

